### ISSUE TITLE
Can't deploy to Heroku: "error: Module not found"

### ISSUE THREAD

**Issue by diguifi** [chibat/heroku-buildpack-deno#14]
Hi! I've been using this buildpack for over a year now, but these last months, I can't seem to deploy.  
Everytime I get this error on the build log:
```
error: Module not found "https://deno.land/std/ws/mod.ts".
    at file:///app/server.ts:2:45
```

Well, you might think "maybe you're a dumass and you should remove this non-existent dependency _"ws/mod.ts"_ from your file `server.ts` at line `2`"  
But, there's no such dependency, heres my latest [server.ts](https://github.com/tiny-devs/tiny-dungeon-online/blob/dev/server.ts) file.

I tried a lot of things, I checked and re-checked a lot of things, I even completely [removed a dependency](https://github.com/tiny-devs/tiny-dungeon-online/issues/179) that in the end had nothing to do with the error.

Another very weird thing is, I tryed re-deploying the same branch, without changin anything and the build log gave me the same error, but in a different [file](https://github.com/tiny-devs/tiny-dungeon-online/blob/dev/server/clientHandler.ts) (which is also not calling that dependency _"ws/mod.ts"_ anywhere)

```
error: Module not found "https://deno.land/std/ws/mod.ts".
    at file:///app/server/clientHandler.ts:1:50
```

My last resort is coming here to ask for help.

---
Just in case it helps, here the entire build log:
```
-----> Building on the Heroku-22 stack
-----> Using buildpack: https://github.com/chibat/heroku-buildpack-deno
-----> https://github.com/chibat/heroku-buildpack-deno app detected
#=#=#                                                                         Archive:  /tmp/build_4d264e83/.heroku/bin/deno.zip
  inflating: /tmp/build_4d264e83/.heroku/bin/deno  
Deno was installed successfully to /tmp/build_4d264e83/.heroku/bin/deno
Manually add the directory to your $HOME/.bashrc (or similar)
  export DENO_INSTALL="/tmp/build_4d264e83/.heroku"
  export PATH="$DENO_INSTALL/bin:$PATH"
Run '/tmp/build_4d264e83/.heroku/bin/deno --help' to get started
Download https://deno.land/std/http/server.ts
Download https://deno.land/std/ws/mod.ts
Download https://deno.land/std@v0.50.0/flags/mod.ts
Download https://deno.land/std/uuid/mod.ts
Warning Implicitly using latest version (0.148.0) for https://deno.land/std/http/server.ts
Download https://deno.land/std@0.148.0/http/server.ts
Warning Implicitly using latest version (0.148.0) for https://deno.land/std/ws/mod.ts
Download https://deno.land/std@0.148.0/ws/mod.ts
Warning Implicitly using latest version (0.148.0) for https://deno.land/std/uuid/mod.ts
Download https://deno.land/std@0.148.0/uuid/mod.ts
Download https://deno.land/std@0.148.0/async/mod.ts
Download https://deno.land/std@0.148.0/uuid/v1.ts
Download https://deno.land/std@0.148.0/uuid/v4.ts
Download https://deno.land/std@0.148.0/uuid/v5.ts
Download https://deno.land/std@v0.50.0/testing/asserts.ts
Download https://deno.land/std@0.148.0/async/abortable.ts
Download https://deno.land/std@0.148.0/async/deadline.ts
Download https://deno.land/std@0.148.0/async/debounce.ts
Download https://deno.land/std@0.148.0/async/deferred.ts
Download https://deno.land/std@0.148.0/async/delay.ts
Download https://deno.land/std@0.148.0/async/mux_async_iterator.ts
Download https://deno.land/std@0.148.0/async/pool.ts
Download https://deno.land/std@0.148.0/async/tee.ts
Download https://deno.land/std@0.148.0/uuid/_common.ts
Download https://deno.land/std@0.148.0/_util/assert.ts
Download https://deno.land/std@0.148.0/bytes/mod.ts
Download https://deno.land/std@v0.50.0/fmt/colors.ts
Download https://deno.land/std@v0.50.0/testing/diff.ts
Download https://deno.land/std@0.148.0/bytes/equals.ts
error: Module not found "https://deno.land/std/ws/mod.ts".
    at file:///app/server.ts:2:45
-----> Discovering process types
       Procfile declares types -> web
-----> Compressing...
       Done: 34.5M
-----> Launching...
       Released v72
       https://tinyland-dev.herokuapp.com/ deployed to Heroku
```

**Comment by chibat** [comment]
Could you try removing "--cached-only" option in the Procfile?
https://github.com/tiny-devs/tiny-dungeon-online/blob/b55a024d9958b976b8e483019bc21531fd88ea26/Procfile

**Comment by diguifi** [comment]
Hi, thanks for answering! I tried it but got the same error unfortunately:  
[updated file](https://github.com/tiny-devs/tiny-dungeon-online/blob/dev/Procfile)
build log:
```
-----> Building on the Heroku-22 stack
-----> Using buildpack: https://github.com/chibat/heroku-buildpack-deno
-----> https://github.com/chibat/heroku-buildpack-deno app detected
#=#=#                                                                         Archive:  /tmp/build_2ed20b12/.heroku/bin/deno.zip
  inflating: /tmp/build_2ed20b12/.heroku/bin/deno  
Deno was installed successfully to /tmp/build_2ed20b12/.heroku/bin/deno
Manually add the directory to your $HOME/.bashrc (or similar)
  export DENO_INSTALL="/tmp/build_2ed20b12/.heroku"
  export PATH="$DENO_INSTALL/bin:$PATH"
Run '/tmp/build_2ed20b12/.heroku/bin/deno --help' to get started
Download https://deno.land/std/http/server.ts
Download https://deno.land/std/ws/mod.ts
Download https://deno.land/std@v0.50.0/flags/mod.ts
Download https://deno.land/std/uuid/mod.ts
Download https://deno.land/std@v0.50.0/testing/asserts.ts
Warning Implicitly using latest version (0.148.0) for https://deno.land/std/uuid/mod.ts
Download https://deno.land/std@0.148.0/uuid/mod.ts
Warning Implicitly using latest version (0.148.0) for https://deno.land/std/http/server.ts
Download https://deno.land/std@0.148.0/http/server.ts
Warning Implicitly using latest version (0.148.0) for https://deno.land/std/ws/mod.ts
Download https://deno.land/std@0.148.0/ws/mod.ts
Download https://deno.land/std@v0.50.0/fmt/colors.ts
Download https://deno.land/std@v0.50.0/testing/diff.ts
Download https://deno.land/std@0.148.0/uuid/v1.ts
Download https://deno.land/std@0.148.0/uuid/v4.ts
Download https://deno.land/std@0.148.0/uuid/v5.ts
Download https://deno.land/std@0.148.0/async/mod.ts
Download https://deno.land/std@0.148.0/_util/assert.ts
Download https://deno.land/std@0.148.0/bytes/mod.ts
Download https://deno.land/std@0.148.0/uuid/_common.ts
Download https://deno.land/std@0.148.0/async/abortable.ts
Download https://deno.land/std@0.148.0/async/deadline.ts
Download https://deno.land/std@0.148.0/async/debounce.ts
Download https://deno.land/std@0.148.0/async/deferred.ts
Download https://deno.land/std@0.148.0/async/delay.ts
Download https://deno.land/std@0.148.0/async/mux_async_iterator.ts
Download https://deno.land/std@0.148.0/async/pool.ts
Download https://deno.land/std@0.148.0/async/tee.ts
Download https://deno.land/std@0.148.0/bytes/equals.ts
error: Module not found "https://deno.land/std/ws/mod.ts".
    at file:///app/server/clientHandler.ts:1:50
-----> Discovering process types
       Procfile declares types -> web
-----> Compressing...
       Done: 34.5M
-----> Launching...
       Released v74
       https://tinyland-dev.herokuapp.com/ deployed to Heroku
```

as a side note, _I felt as if the build was suspiciously fast_
